import math

import networkx as nx
import matplotlib.pyplot as plt
import matplotlib
import math

# G = nx.icosahedral_graph()
# # pos = nx.planar_layout(G)
# pos = nx.kamada_kawai_layout(G)
# nx.draw(G, pos=pos, with_labels=True, node_color='skyblue', node_size=150, font_size=12, font_weight='bold', edge_color='gray')
# # plt.show()
#
# # H = nx.truncated_tetrahedron_graph()
# # H = nx.tetrahedral_graph()
# # pos = nx.planar_layout(H)
# # nx.draw(H, pos=pos, with_labels=True, node_color='skyblue', node_size=150, font_size=12, font_weight='bold', edge_color='gray')
# # plt.show()
# # X = nx.hexagonal_lattice_graph(1,1)
#
# #
# # # Draw the graph
# # nx.draw(C, pos=pos, with_labels=True, node_color='skyblue', node_size=150, font_size=12, font_weight='bold', edge_color='gray')
# # plt.title("Tetrahedral Graph")
# # plt.show()
#
# G = nx.Graph()
# G.add_nodes_from([0,1,2,3])
# G.add_edge(1,3, length = (math.sqrt(6)))
# G.add_edge(1,2, length = (math.sqrt(6)))
# G.add_edge(1,0, length = (math.sqrt(6)))
# G.add_edge(0,2, length = 2)
# G.add_edge(0,3, length = 2)
# G.add_edge(2,3, length = 2)
#
# pos = nx.planar_layout(G)
# nx.draw(G, pos)
# nx.draw(G, pos, with_labels= True, node_color='skyblue', node_size=150, font_size=12, font_weight='bold', edge_color='gray')
# nx.draw_networkx_edge_labels(G, pos)
# plt.show()

G = nx.Graph()
G.add_nodes_from(range(0,9))
G.add_edge(0,1,length=2)
G.add_edge(1,2,length=2)
G.add_edge(2,3,length=2)
G.add_edge(3,4,length=2)
G.add_edge(4,5,length=2)
G.add_edge(5,0,length=2)
G.add_edge(5,6,length=0.726)
G.add_edge(1,7,length=0.726)
G.add_edge(3,8,length=0.726)
G.add_edge(2,7,length=1.754)
G.add_edge(0,7,length=1.754)
G.add_edge(0,6,length=1.754)
G.add_edge(4,6,length=1.754)
G.add_edge(4,8,length=1.754)
G.add_edge(8,2,length=1.754)
G.add_edge(6,8,length=2.208)
G.add_edge(7,8,length=2.208)
G.add_edge(6,7,length=2.208)

pos = nx.spring_layout(G)
nx.draw(G, pos, with_labels= True, node_color='skyblue', node_size=150, font_size=12, font_weight='bold', edge_color='gray')
# nx.draw_networkx_edge_labels(G, pos)
# plt.show()


T1 = nx.Graph()
T1.add_nodes_from([0, 1, 9, 10])
height = math.sqrt(2/3)*2
T1.add_edge(10,9, length = height)
T1.add_edge(9,1, length = height)
T1.add_edge(0,9, length = height)
T1.add_edge(0,1, length = 2)
T1.add_edge(0,10, length = 2)
T1.add_edge(10,1, length = 2)
pos = nx.planar_layout(T1)
nx.draw(T1, pos, with_labels= True, node_color='skyblue', node_size=150, font_size=12, font_weight='bold', edge_color='gray')

GT1 = nx.compose(G,T1)
pos = nx.spring_layout(GT1)
nx.draw(GT1, pos, with_labels= True, node_color='skyblue', node_size=150, font_size=12, font_weight='bold', edge_color='gray')
# plt.show()

T2 = nx.Graph()
T2.add_nodes_from([1, 2, 11, 12])
height = math.sqrt(2/3)*2
T2.add_edge(11,2, length = height)
T2.add_edge(11,1, length = height)
T2.add_edge(11,12, length = height)
T2.add_edge(1,2, length = 2)
T2.add_edge(2,12, length = 2)
T2.add_edge(12,1, length = 2)
pos = nx.planar_layout(T2)
nx.draw(T2, pos, with_labels = True, node_color='skyblue', node_size=150, font_size=12, font_weight='bold', edge_color='gray')

GT1T2 = nx.compose(GT1,T2)
pos = nx.spring_layout(GT1T2)
nx.draw(GT1T2, pos, with_labels= True, node_color='skyblue', node_size=150, font_size=12, font_weight='bold', edge_color='gray')
# plt.show()

H = nx.Graph()
H.add_nodes_from([10, 1, 12, 21, 22, 23, 24, 25, 26])
H.add_edge(10, 1,length=2)
H.add_edge(10,21,length=2)
H.add_edge(21,22,length=2)
H.add_edge(22,23,length = 2)
H.add_edge(23,12,length=2)
H.add_edge(12,1,length=2)
H.add_edge(10,25,length=0.726)
H.add_edge(22,24,length=0.726)
H.add_edge(12,26,length=0.726)
H.add_edge(21,25,length=1.754)
H.add_edge(21,24,length=1.754)
H.add_edge(24,23, length=1.754)
H.add_edge(23,26,length=1.754)
H.add_edge(26,1, length=1.754)
H.add_edge(1,25,length=1.754)
H.add_edge(25,24,length=2.208)
H.add_edge(24,26, length=2.208)
H.add_edge(26,25,length=2.208)
pos = nx.spring_layout(H)
nx.draw(H, pos, with_labels= True, node_color='skyblue', node_size=150, font_size=12, font_weight='bold', edge_color='gray')

GT1T2H = nx.disjoint_union(GT1T2,H)
pos = nx.spring_layout(GT1T2H)
nx.draw(GT1T2H, pos, with_labels= False, node_color='skyblue', node_size=150, font_size=12, font_weight='bold', edge_color='gray')
plt.show()

# T1 = nx.Graph()
# T1.add_nodes_from([0, 1, 9, 10])
# height = math.sqrt(2/3)*2
# T1.add_edge(10,9, length = height)
# T1.add_edge(9,1, length = height)
# T1.add_edge(0,9, length = height)
# T1.add_edge(0,1, length = 2)
# T1.add_edge(0,10, length = 2)
# T1.add_edge(10,1, length = 2)
# pos = nx.planar_layout(T1)
# nx.draw(T1, pos, with_labels= True, node_color='skyblue', node_size=150, font_size=12, font_weight='bold', edge_color='gray')
# nx.draw_networkx_edge_labels(T1, pos)
# plt.show()